# Generated by Django 3.2.5 on 2021-07-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_post_snippts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippts',
            field=models.CharField(max_length=255),
        ),
    ]
