# Generated by Django 3.2.5 on 2021-07-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_alter_post_snippts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippts',
        ),
    ]
