# Generated by Django 3.2.5 on 2021-07-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_remove_post_snippts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippt',
            field=models.CharField(default='this is snipt', max_length=255),
        ),
    ]
