# Generated by Django 3.2.5 on 2021-07-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_post_snippt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippt',
            field=models.CharField(default='this is snippt', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
