# Generated by Django 3.2.5 on 2021-07-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_auto_20210712_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='we_chat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
